GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6IjY0N2RkMzA3ZDMzODVlYzc2ZGQ3OGYyNCIsImlhdCI6MTY4NjIyNzk4MiwiZXhwIjoxNjg2MjMxNTgyfQ.ClxRnom45U6xTPCahktMAV96N0aESme1mplObpUuGaE

{
    "content": "Mongoose is cool",
    "important": true
    
}

###
DELETE http://localhost:3001/api/notes/6469fb184988cc39ae2cf103
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6IjY0N2RkMzA3ZDMzODVlYzc2ZGQ3OGYyNCIsImlhdCI6MTY4NjIyNzk4MiwiZXhwIjoxNjg2MjMxNTgyfQ.ClxRnom45U6xTPCahktMAV96N0aESme1mplObpUuGaE

###
PUT http://localhost:3001/api/notes/646769df7807db59c6152e52 HTTP/1.1
content-type: application/json

{
    "content": "test",
    "important": true
}


